name: Continuous Integration Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        working-directory: ./react-redux-login-counter

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - test-name: "Counter Test"
            test-path: "src/features/counter/__tests__/Counter.test.js"
          - test-name: "Login Test"
            test-path: "src/features/login/__tests__/Login.test.js"
          - test-name: "Post Test"
            test-path: "src/features/posts/__tests__/Post.test.js"
          - test-name: "PostDetail Test"
            test-path: "src/features/posts/__tests__/PostDetail.test.js"
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies (cache hit)
        run: echo "Dependencies should be cached"

      - name: Run ${{ matrix.test-name }}
        run: npm run test -- ${{ matrix.test-path }}
        working-directory: ./react-redux-login-counter

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Establish SSH Connection and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "SSH connection established."
            cd /home/ubuntu/html/react-jest/react-redux-login-counter/
            git pull origin main
            echo "Deployment completed successfully."
